name: SonarQube analysis

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  pull-requests: read # allows SonarQube to decorate PRs with analysis results

jobs:
  Analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Analyze with SonarQube
        uses: SonarSource/sonarqube-scan-action@7295e71c9583053f5bf40e9d4068a0c974603ec8
        env:
          GITHUB_TOKEN: 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
          SONAR_TOKEN: 4a48df7f7b518facc8744d6e33294fbc3f784f9c 
          SONAR_HOST_URL: http://23.102.159.162:9000   # add the URL of your instance to the secrets of this repo with the name SONAR_HOST_URL (Settings > Secrets > Actions > add new repository secret)
      - name: jk
        run: mvn sonar:sonar \
                -Dsonar.projectKey=harshit1 \
                -Dsonar.host.url=http://23.102.159.162:9000 \
                -Dsonar.login=4a48df7f7b518facc8744d6e33294fbc3f784f9c
            
            

