name: SonarQube analysis

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  pull-requests: read # allows SonarQube to decorate PRs with analysis results

jobs:
  Analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Analyze with SonarQube
        uses: kitabisa/sonarqube-action@master
        with:
             host: http://23.102.159.162:9000   
             login: 4a48df7f7b518facc8744d6e33294fbc3f784f9c 
             projectBaseDir: "maven-basic/src/"
             projectKey: "harshit1"
        
    
            
            

